name: pirl
channels:
  - pytorch
  - defaults
dependencies:
  - attrs=17.4.0
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - cffi=1.11.4
  - cycler=0.10.0
  - dbus=1.12.2
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - gitdb2=2.0.0
  - gitpython=2.1.3
  - glib=2.53.6
  - icu=58.2
  - intel-openmp=2018.0.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libpng=1.6.34
  - libtiff=4.0.9
  - libxml2=2.9.7
  - matplotlib=2.2.0
  - mkl=2018.0.1
  - ncurses=6.0
  - numpy=1.14.1
  - olefile=0.45.1
  - openssl=1.0.2n
  - pandas=0.22.0
  - patsy=0.5.0
  - pcre=8.41
  - pillow=5.0.0
  - pip=9.0.1
  - pluggy=0.6.0
  - py=1.5.2
  - pycparser=2.18
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pytest=3.4.2
  - python=3.6.4
  - python-dateutil=2.7.0
  - pytz=2018.3
  - qt=5.6.2
  - readline=7.0
  - scipy=1.0.0
  - seaborn=0.8.1
  - setuptools=38.5.1
  - sip=4.18.1
  - six=1.11.0
  - smmap2=2.0.1
  - sqlite=3.22.0
  - statsmodels=0.8.0
  - tk=8.6.7
  - tornado=5.0
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - pytorch=0.3.1
  - torchvision=0.2.0
  - pip:
    - chardet==3.0.4
    - future==0.16.0
    - gym==0.9.7
    - idna==2.6
    - pyglet==1.3.1
    - pyyaml==3.12
    - requests==2.18.4
    - torch==0.3.1.post2
    - urllib3==1.22
