name: pirl
channels:
  - pytorch
  - defaults
dependencies:
  - apipkg=1.4
  - attrs=17.4.0
  - bleach=1.5.0
  - bzip2=1.0.6
  - ca-certificates=2017.08.26
  - cairo=1.14.12
  - certifi=2018.1.18
  - cffi=1.11.5
  - cudatoolkit=8.0
  - cudnn=7.0.5
  - cycler=0.10.0
  - dbus=1.12.2
  - decorator=4.2.1
  - entrypoints=0.2.3
  - execnet=1.5.0
  - expat=2.2.5
  - ffmpeg=3.4
  - fontconfig=2.12.6
  - freetype=2.8
  - gitdb2=2.0.0
  - gitpython=2.1.3
  - glib=2.53.6
  - gmp=6.1.2
  - graphite2=1.3.10
  - gst-plugins-base=1.12.4
  - gstreamer=1.12.4
  - harfbuzz=1.7.6
  - hdf5=1.10.1
  - html5lib=0.9999999
  - icu=58.2
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.1.2
  - jasper=1.900.1
  - jedi=0.11.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.2
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libopus=1.2.1
  - libpng=1.6.34
  - libprotobuf=3.5.1
  - libsodium=1.0.15
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libvpx=1.6.1
  - libxcb=1.12
  - libxml2=2.9.7
  - line_profiler=2.0
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - more-itertools=4.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nccl=1.3.4
  - ncurses=6.0
  - notebook=5.4.0
  - numpy=1.14.2
  - olefile=0.45.1
  - opencv=3.3.1
  - openssl=1.0.2o
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.1.1
  - path.py=11.0
  - patsy=0.5.0
  - pcre=8.41
  - pexpect=4.4.0
  - pickleshare=0.7.4
  - pillow=5.0.0
  - pip=9.0.1
  - pixman=0.34.0
  - pluggy=0.6.0
  - prompt_toolkit=1.0.15
  - protobuf=3.5.1
  - ptyprocess=0.5.2
  - py=1.5.3
  - pycparser=2.18
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pytest=3.5.0
  - pytest-forked=0.2
  - pytest-xdist=1.22.1
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.3
  - pyzmq=17.0.0
  - qt=5.6.2
  - qtconsole=4.3.1
  - readline=7.0
  - scipy=1.0.1
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.0.1
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - smmap2=2.0.1
  - sqlite=3.22.0
  - statsmodels=0.8.0
  - tensorflow-gpu=1.4.1
  - tensorflow-gpu-base=1.4.1
  - tensorflow-tensorboard=1.5.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.30.0
  - widgetsnbextension=3.1.4
  - xarray=0.10.2
  - xz=5.2.3
  - zeromq=4.2.3
  - zlib=1.2.11
  - cuda90=1.0
  - pytorch=0.3.1
  - torchvision=0.2.0
  - pip:
    - adversarial-irl==0.1
    - atari-py==0.1.1
    - baselines==0.1.5
    - cached-property==1.4.0
    - chardet==3.0.4
    - click==6.7
    - cloudpickle==0.5.2
    - cython==0.28.1
    - dill==0.2.7.1
    - enum34==1.1.6
    - future==0.16.0
    - glfw==1.6.0
    - gym==0.10.4
    - idna==2.6
    - imageio==2.3.0
    - joblib==0.11
    - mpi4py==3.0.0
    - mujoco-py==1.50.1.41
    - progressbar2==3.36.0
    - pygame==1.9.3
    - pyglet==1.3.1
    - pyopengl==3.1.0
    - pyprind==2.11.2
    - python-utils==2.3.0
    - pyyaml==3.12
    - requests==2.18.4
    - rllab==0.1.0
    - tensorflow==1.4.1
    - torch==0.3.1.post2
    - tqdm==4.19.9
    - urllib3==1.22
    - zmq==0.0.0
