name: pirl 
channels:
  - pytorch
  - defaults
dependencies:
  - alabaster=0.7.10
  - apipkg=1.4
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - babel=2.5.3
  - backcall=0.1.0
  - bleach=2.1.3
  - bokeh=0.12.16
  - boto3=1.5.32
  - botocore=1.8.46
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - cmake=3.11.1
  - cryptography=2.2.2
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - curl=7.59.0
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - entrypoints=0.2.3
  - execnet=1.5.0
  - expat=2.2.5
  - ffmpeg=3.4
  - fontconfig=2.12.6
  - freeglut=2.8.1
  - freetype=2.8
  - gitdb2=2.0.3
  - gitpython=2.1.9
  - glib=2.56.1
  - gmp=6.1.2
  - graphite2=1.3.11
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.7.6
  - hdf5=1.10.1
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - imagesize=1.0.0
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jasper=2.0.14
  - jedi=0.12.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcurl=7.59.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libglu=9.0.0
  - libopus=1.2.1
  - libpng=1.6.34
  - libprotobuf=3.5.2
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libuv=1.20.0
  - libvpx=1.6.1
  - libxcb=1.13
  - libxml2=2.9.8
  - line_profiler=2.1.2
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - more-itertools=4.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nccl=1.3.5
  - ncurses=6.1
  - ninja=1.8.2
  - notebook=5.5.0
  - numpy=1.14.2
  - numpydoc=0.8.0
  - olefile=0.45.1
  - opencv=3.3.1
  - openssl=1.0.2o
  - packaging=17.1
  - pandas=0.23.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - path.py=11.0.1
  - patsy=0.5.0
  - pcre=8.42
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=10.0.1
  - pixman=0.34.0
  - pluggy=0.6.0
  - prompt_toolkit=1.0.15
  - protobuf=3.5.2
  - ptyprocess=0.5.2
  - py=1.5.3
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytest=3.5.1
  - pytest-forked=0.2
  - pytest-xdist=1.22.2
  - python=3.6.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.9.5
  - qtconsole=4.3.1
  - readline=7.0
  - requests=2.18.4
  - rhash=1.3.5
  - s3transfer=0.1.13
  - scipy=1.1.0
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.1.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - smmap2=2.0.3
  - snowballstemmer=1.2.1
  - sphinx=1.7.4
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - sqlite=3.23.1
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.2.1
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - cuda90=1.0
  - pytorch=0.4.0
  - torchvision=0.2.1
  - pip:
    - absl-py==0.2.1
    - git+git://github.com/AdamGleave/inverse_rl.git@master#egg=adversarial-irl
    - astor==0.6.2
    - atari-py==0.1.1
    - git+git://github.com/openai/baselines.git@9cb7ec#egg=baselines
    - cached-property==1.4.0
    - click==6.7
    - cloudpickle==0.5.2
    - colorama==0.3.9
    - cython==0.28.1
    - dill==0.2.7.1
    - flatbuffers==2015.12.22.1
    - funcsigs==1.0.2
    - future==0.16.0
    - gast==0.2.0
    - glfw==1.6.0
    - grpcio==1.12.0
    - git+git://github.com/AdamGleave/gym.git@all-fixes#egg=gym
    - imageio==2.3.0
    - joblib==0.11
    - mpi4py==3.0.0
    - mujoco-py==1.50.1.56
    - portalocker==1.2.0
    - progressbar2==3.36.0
    - psutil==5.4.5
    - pyarrow==0.9.0
    - pygame==1.9.3
    - pyglet==1.3.1
    - pyopengl==3.1.0
    - pyprind==2.11.2
    - python-utils==2.3.0
    - pyyaml==3.12
    - ray==0.4.0
    - redis==2.10.6
    - git+git://github.com/AdamGleave/rllab.git@master#egg=rllab
    - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.8.0-cp36-cp36m-linux_x86_64.whl
    - termcolor==1.1.0
    - torch==0.4.0
    - tqdm==4.19.9
    - zmq==0.0.0
